# Generated by Django 3.1.5 on 2021-01-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210128_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='motto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
