# Generated by Django 3.1.5 on 2021-03-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='battle_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='battle_win',
            field=models.IntegerField(default=0),
        ),
    ]
