# Generated by Django 3.1.5 on 2021-03-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='battle_id',
            field=models.IntegerField(default=None),
        ),
    ]
