# Generated by Django 3.1.5 on 2021-03-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_id', models.IntegerField()),
                ('player1_code', models.TextField()),
                ('player1_endtime', models.DateTimeField()),
                ('player2_id', models.IntegerField()),
                ('player2_code', models.TextField()),
                ('player2_endtime', models.DateTimeField()),
                ('result', models.TextField()),
                ('pro_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'battle',
            },
        ),
        migrations.CreateModel(
            name='BattleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pro_id', models.IntegerField(default=None)),
                ('channels_name', models.TextField()),
                ('opponent_channels_name', models.TextField(default=None)),
                ('waiting', models.BooleanField(default=True)),
                ('battle_id', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'battle_user',
            },
        ),
    ]
